"""
Django settings for starter project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-izg3h9my%v4q&nzlts4&31+06*n4!w_k%ow0*o*po5qqk^1(0i",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'starter.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'starter.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Default: SQLite. To use another database, comment this block and uncomment
# exactly one matching block below.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.getenv("SQLITE_NAME", BASE_DIR / "db.sqlite3"),
    }
}

# PostgreSQL. Also uncomment the postgres service in docker-compose.yml or
# docker-compose-prod.yml.
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.postgresql",
#         "NAME": os.getenv("POSTGRES_DB", "django_template"),
#         "USER": os.getenv("POSTGRES_USER", "django"),
#         "PASSWORD": os.getenv("POSTGRES_PASSWORD", "django"),
#         "HOST": os.getenv("POSTGRES_HOST", "postgres"),
#         "PORT": os.getenv("POSTGRES_PORT", "5432"),
#     }
# }

# MySQL. Also uncomment the mysql service in docker-compose.yml or
# docker-compose-prod.yml.
# If you use PyMySQL instead of mysqlclient, uncomment these two lines:
# import pymysql
# pymysql.install_as_MySQLdb()
# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.mysql",
#         "NAME": os.getenv("MYSQL_DATABASE", "django_template"),
#         "USER": os.getenv("MYSQL_USER", "django"),
#         "PASSWORD": os.getenv("MYSQL_PASSWORD", "django"),
#         "HOST": os.getenv("MYSQL_HOST", "mysql"),
#         "PORT": os.getenv("MYSQL_PORT", "3306"),
#         "OPTIONS": {
#             "charset": "utf8mb4",
#         },
#     }
# }

# MongoDB. Django's built-in ORM does not use MongoDB; uncomment this block
# when service-layer code needs a Mongo client. Also uncomment the mongodb
# service in docker-compose.yml or docker-compose-prod.yml.
# MONGODB = {
#     "NAME": os.getenv("MONGODB_DATABASE", "django_template"),
#     "HOST": os.getenv("MONGODB_HOST", "mongodb"),
#     "PORT": int(os.getenv("MONGODB_PORT", "27017")),
#     "USER": os.getenv("MONGODB_USER", ""),
#     "PASSWORD": os.getenv("MONGODB_PASSWORD", ""),
#     "URI": os.getenv("MONGODB_URI", ""),
# }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
